title: Ray Chang
email: ray120424@gmail.com
description: >- 
 這是我的個人網站，裡面詳細的介紹了我從小到大的經歷、做過的事情，還有現在以及未來的發展。
baseurl: "/activity_reflections"
remote_theme: jekyll/minima@v2.5.1
markdown: kramdown
plugins:
  - jekyll-remote-theme
  - jekyll-feed
header_pages:
  - robot/index.md
  - sailing/index.md
  - bicycle/index.md
  - learning_schedule/index.md
  - bus/index.md
  - program/index.md